# Generated by Django 4.0.4 on 2022-05-28 23:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('texto', models.TextField()),
                ('categoria', models.CharField(choices=[('Deporte', 'Deporte'), ('Cientifico', 'Cientifico'), ('Ciencia y Tecnologia', 'Ciencia y Tecnologia'), ('Musica', 'Musica'), ('Arte', 'Arte'), ('Entretenimiento', 'Entretenimiento'), ('Opinion', 'Opinion')], max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='imagen/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'PNG'])])),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
