# Generated by Django 4.0.4 on 2022-05-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_articulo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='creado',
            field=models.DateField(auto_now=True),
        ),
    ]
